
-- ============================================================================
-- MIGRATION SQL - PROJETO JARDEL BARBER
-- Execute este script no SQL Editor do Supabase para configurar o banco.
-- ============================================================================

-- 1. LIMPEZA (Cuidado: Remove tabelas existentes)
DROP TABLE IF EXISTS revenue CASCADE;
DROP TABLE IF EXISTS appointments CASCADE;
DROP TABLE IF EXISTS services CASCADE;
DROP TABLE IF EXISTS professionals CASCADE;
DROP TABLE IF EXISTS tenant_settings CASCADE;
DROP TABLE IF EXISTS tenants CASCADE;

-- 2. CRIAÇÃO DAS TABELAS

-- Tabela: tenants
CREATE TABLE tenants (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL,
  slug text UNIQUE NOT NULL,
  status text DEFAULT 'ativo',
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
  -- Campos utilizados pelo Frontend
  logo_url text,
  header_bg_url text
);

-- Tabela: tenant_settings
CREATE TABLE tenant_settings (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id bigint REFERENCES tenants(id) ON DELETE CASCADE NOT NULL,
  work_start text DEFAULT '09:00',
  work_end text DEFAULT '20:00',
  location_address text,
  location_city text,
  location_state text,
  social_instagram text,
  social_facebook text,
  whatsapp_number text,
  pix_copy_paste text,
  pix_qr_url text,
  timezone text DEFAULT 'America/Sao_Paulo',
  slot_step_min int DEFAULT 30,
  buffer_min int DEFAULT 15,
  -- Campos solicitados no prompt
  logo text,
  primary_color text
);

-- Tabela: professionals
CREATE TABLE professionals (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id bigint REFERENCES tenants(id) ON DELETE CASCADE NOT NULL,
  name text NOT NULL,
  specialty text,
  avatar_url text,
  active boolean DEFAULT true
);

-- Tabela: services
CREATE TABLE services (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id bigint REFERENCES tenants(id) ON DELETE CASCADE NOT NULL,
  name text NOT NULL,
  price numeric NOT NULL,
  duration_min int NOT NULL,
  image_url text,
  active boolean DEFAULT true
);

-- Tabela: appointments
CREATE TABLE appointments (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id bigint REFERENCES tenants(id) ON DELETE CASCADE NOT NULL,
  user_name text NOT NULL,
  user_email text,
  user_phone text,
  service_id bigint REFERENCES services(id) ON DELETE SET NULL,
  professional_id bigint REFERENCES professionals(id) ON DELETE SET NULL,
  start_time timestamp with time zone NOT NULL,
  end_time timestamp with time zone NOT NULL,
  status text DEFAULT 'pendente',
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
  receipt_url text
);

-- Tabela: revenue (Necessária para o módulo Financeiro do App)
CREATE TABLE revenue (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  date timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
  description text NOT NULL,
  category text,
  amount numeric NOT NULL,
  payment_method text
);

-- 3. DESABILITAR RLS (Row Level Security) - COMO SOLICITADO
ALTER TABLE tenants DISABLE ROW LEVEL SECURITY;
ALTER TABLE tenant_settings DISABLE ROW LEVEL SECURITY;
ALTER TABLE professionals DISABLE ROW LEVEL SECURITY;
ALTER TABLE services DISABLE ROW LEVEL SECURITY;
ALTER TABLE appointments DISABLE ROW LEVEL SECURITY;
ALTER TABLE revenue DISABLE ROW LEVEL SECURITY;

-- 4. DADOS INICIAIS (SEED) - JARDEL BARBER (ID=1)

-- Tenant
INSERT INTO tenants (name, slug, status, logo_url, header_bg_url)
VALUES (
  'Jardel Barber', 
  'jardel-barber', 
  'ativo',
  'https://images.unsplash.com/photo-1503951914875-452162b0f3f1',
  'https://images.unsplash.com/photo-1599351431247-f10b21817021'
);

-- Settings
INSERT INTO tenant_settings (tenant_id, work_start, work_end, location_address, location_city, location_state, whatsapp_number, slot_step_min)
VALUES (1, '09:00', '20:00', 'Av. Principal, 1000', 'São Paulo', 'SP', '5511999999999', 30);

-- Professionals
INSERT INTO professionals (tenant_id, name, specialty, active)
VALUES 
(1, 'Jardel', 'Corte Master', true),
(1, 'Lucas', 'Barba e Acabamento', true);

-- Services
INSERT INTO services (tenant_id, name, price, duration_min, image_url, active)
VALUES 
(1, 'Corte Degrade', 50.00, 45, 'https://images.unsplash.com/photo-1621605815971-fbc98d665033', true),
(1, 'Barba Completa', 35.00, 30, 'https://images.unsplash.com/photo-1503951914875-452162b0f3f1', true),
(1, 'Combo (Corte + Barba)', 75.00, 60, NULL, true);
